version: '3'
services:
  todoback:
    build: back-end/
    ports:
      - "3001:3001"
  todofront:
    build: front-end/
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
    - todoback
  todotests:
    build: tests/
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront